spring.datasource.url=jdbc:postgresql://localhost:5432/indeed
spring.datasource.username=postgres
spring.datasource.password=root

#spring.datasource.url=jdbc:mysql://localhost:3306/indeed
#spring.datasource.username=root
#spring.datasource.password=Mysql@1234
server.port=9090
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver